"""Plain-English explanation for each catalogue check.

Keyed by check number. Each entry says, in one or two sentences, *what* the check
looks at and *why it matters* for SEO — so the audit workbook is actionable
without prior knowledge of every issue type.
"""

from __future__ import annotations

DESCRIPTIONS: dict[int, str] = {
    1: "Detects sites that hide content behind a cookie/consent wall so bots receive near-empty pages. Search engines may then index little or no content.",
    2: "Flags URLs returning 403/429/503 or WAF challenge responses, which usually mean a security tool is blocking the crawler (and potentially Googlebot) from accessing pages.",
    3: "Checks whether the page served to a search-engine user-agent differs from the one served to a normal user-agent (cloaking), which violates search guidelines and can cause penalties.",
    4: "Validates that robots.txt uses correct directive syntax. Malformed lines can be ignored or misinterpreted, unintentionally allowing or blocking crawling.",
    5: "Confirms a robots.txt file exists. A missing file isn't fatal, but it removes your ability to guide crawlers and declare sitemaps.",
    6: "Finds pages whose canonical tag points to a URL that is itself non-indexable (noindex or non-200). This sends conflicting signals and can drop pages from the index.",
    7: "Detects canonical link elements placed outside the <head>. Browsers/Google only honour canonicals in the head, so these are ignored.",
    8: "Flags canonical tags pointing at a staging/dev domain. This tells Google to index the wrong (often blocked) environment, removing live pages from search.",
    9: "Finds canonicals pointing to a third-party domain, which hands ranking signals to another site and can deindex your own pages.",
    10: "Identifies faceted/filter URLs that are not canonicalised back to a clean URL, risking duplicate content and crawl-budget waste.",
    11: "Identifies sort/order-parameter URLs not canonicalised to the clean version, another common source of duplicate content.",
    12: "Flags malformed canonical values (spaces, multiple tags, non-URLs). Broken canonicals are ignored, leaving duplicate-content signals unresolved.",
    13: "HEAD-checks referenced JavaScript/CSS files for non-200 responses. Broken assets can break rendering, layout, and functionality for users and bots.",
    14: "Checks whether robots.txt blocks CSS/JS. Google needs these to render pages; blocking them can hurt how pages are understood and ranked.",
    15: "Looks for pages that fail to render (JS errors) in a headless browser. Content that never renders can't be indexed.",
    16: "Detects navigation that only exists after JavaScript runs. If links aren't in the static HTML, crawlers may not discover linked pages.",
    17: "Flags infinite-scroll/pagination without crawlable links (rel=next/prev or <a> hrefs), which can leave deep content undiscovered.",
    18: "Finds internal links carrying UTM tracking parameters. These create duplicate URLs and pollute analytics; internal links shouldn't be tagged.",
    19: "Detects filter URLs where parameters appear in inconsistent order, multiplying duplicate URLs for the same content.",
    20: "Finds internal links pointing to on-site search result pages, which are low-value, crawl-wasting URLs Google prefers not to index.",
    21: "Catches other rendering-blocking errors that stop a page displaying in a headless browser, preventing indexation.",
    22: "Detects content present only after JavaScript execution and hidden from the static HTML, which crawlers may miss.",
    23: "Flags pages with more than one <head> element. Duplicate/invalid heads can cause the browser to ignore metadata like canonicals and titles.",
    24: "Finds canonicals pointing away from the primary domain set, which can consolidate signals onto the wrong site.",
    25: "Largest Contentful Paint: measures how quickly the main content loads. Poor LCP hurts user experience and is a Core Web Vitals ranking signal.",
    26: "Cumulative Layout Shift: measures unexpected layout movement. High CLS frustrates users and is a Core Web Vitals ranking signal.",
    27: "Checks that images are served at appropriate dimensions rather than scaled down in the browser, which wastes bandwidth and slows loading.",
    28: "Identifies render-blocking scripts/stylesheets in the head that delay first paint. Deferring them improves load speed.",
    29: "Flags images that aren't efficiently compressed/encoded, increasing page weight and slowing load times.",
    30: "Validates structured data (JSON-LD/microdata) against schema.org. Invalid markup can forfeit rich results in search.",
    31: "Checks for Organization schema, which helps search engines understand your brand entity and can power knowledge-panel features.",
    32: "Checks for LocalBusiness schema, important for local search visibility (advisory unless the site is a local business).",
    33: "Detects <title> tags placed outside the <head>, where they may be ignored, leaving pages without an effective title.",
    34: "Finds pages missing an H1 heading. H1s help users and search engines understand the primary topic of a page.",
    35: "Detects content injected via CSS ::before/::after. Such content is decorative and generally not indexable.",
    36: "Checks whether Google Search Console is verified/active, which is required to monitor performance and submit sitemaps.",
    37: "Finds sitemap URLs that return 200 but show thin/'not found' content (soft 404s), wasting crawl budget and confusing indexing.",
    38: "Checks that robots.txt declares your XML sitemap(s) via a Sitemap: directive, aiding discovery of your URLs.",
    39: "Validates that Sitemap: URLs in robots.txt actually resolve and parse; broken references hinder URL discovery.",
    40: "Flags relative (non-absolute) canonical URLs. Canonicals should be absolute; relative ones can be misresolved.",
    41: "HEAD-checks image sources for non-200 responses. Broken images harm user experience and can indicate content issues.",
    42: "Assesses whether JavaScript is minified. Unminified JS increases page weight and slows load times.",
    43: "Assesses whether CSS is minified. Unminified CSS increases page weight and slows load times.",
    44: "Checks that text responses use gzip/brotli compression. Uncompressed responses are larger and slower to download.",
    45: "Checks static assets for an efficient cache policy (cache-control/expires). Weak caching forces repeat downloads and slows repeat visits.",
    46: "Detects document.write(), which blocks parsing and can break rendering, especially on slow connections.",
    47: "Flags fonts not served in the modern woff2 format, which is smaller and faster than older font formats.",
    48: "Flags 5xx server errors. These pages are inaccessible to users and search engines and can be dropped from the index.",
    49: "Detects HTTPS pages that reference HTTP resources (mixed content), which browsers may block and which weakens security signals.",
    50: "Finds malformed URLs (invalid characters/structure) that can break crawling, linking, and indexing.",
    51: "Advisory: checks for preconnect resource hints, which can speed up connections to key third-party origins.",
    52: "Checks the viewport meta tag includes width and initial-scale. Without it, pages aren't mobile-friendly, hurting mobile rankings.",
    53: "Flags animated GIFs that would be smaller and faster as video formats (MP4/WebM), reducing page weight.",
    54: "Detects CSS @import for fonts/stylesheets, which chains requests and delays rendering versus <link>.",
    55: "Finds HTML markup inside meta descriptions. Tags are stripped or displayed literally, harming snippet quality.",
    56: "Flags pages with multiple meta description tags, which is ambiguous and can lead to the wrong snippet being used.",
    57: "Checks whether an XML sitemap is submitted in Google Search Console, aiding indexing and coverage reporting.",
    58: "Flags sitemaps exceeding 50,000 URLs or 50 MB, the protocol limits; oversized sitemaps may be ignored.",
    59: "Detects redirect chains that end in a 4xx/5xx (broken redirects), losing users and link equity.",
    60: "Detects redirect loops (a URL redirecting back to itself/chain), which make pages permanently inaccessible.",
    61: "Lists URLs with a nosnippet directive, which prevents Google showing a text snippet — sometimes intended, often not.",
    62: "Lists URLs with a noarchive directive, which stops Google caching the page. Usually harmless but worth confirming.",
    63: "Finds pages that are both noindex and canonicalised elsewhere — conflicting directives that confuse indexing.",
    64: "Flags filter links that are freely crawlable (no nofollow/JS handling), letting crawlers waste budget on faceted duplicates.",
    65: "Flags sort/order links that are freely crawlable, another source of crawl-budget waste on duplicate URLs.",
    66: "Finds internal nofollow links pointing to indexable pages, which needlessly withholds internal link equity.",
    67: "Finds indexable on-site search URLs, which are low-value pages Google recommends keeping out of the index.",
    68: "Finds indexable URLs containing session IDs, which create infinite duplicate URLs and dilute crawl budget.",
    69: "Compares mobile vs desktop content for inconsistencies. Under mobile-first indexing, missing mobile content can hurt rankings.",
    70: "Detects product URL variations (parameter variants) that duplicate the same product, splitting ranking signals.",
    71: "Detects intrusive interstitials/pop-ups that cover content on load, which can trigger a mobile ranking demotion.",
    72: "Finds 4xx pages that have backlinks, representing lost link equity that could be recovered with redirects.",
    73: "Checks how discontinued products are handled (404 vs 301). Poor handling loses traffic and link equity.",
    74: "Detects meta descriptions placed outside the <head>, where they are ignored, leaving pages without a snippet source.",
    75: "Detects titles that change via JavaScript after load, which can cause unstable/unexpected titles in search.",
    76: "Flags pages with multiple <title> tags, which is ambiguous and can lead to the wrong title being shown.",
    77: "Checks that an XML sitemap exists (via robots.txt or common paths). Sitemaps help search engines discover URLs.",
    78: "Validates XML sitemap formatting. Parse errors can prevent search engines reading your URL list.",
    79: "Finds indexable pages missing a canonical tag. Explicit canonicals help consolidate duplicate signals.",
    80: "Checks whether robots.txt blocks image paths, which can stop images ranking in Google Images.",
    81: "Detects navigation via JavaScript onclick on anchors without href, which crawlers can't follow.",
    82: "Tests that http/non-www/trailing-slash variants redirect to the canonical version, preventing duplicate-URL indexing.",
    83: "Flags excessive crawling of .json files, which usually shouldn't be indexed and can waste crawl budget.",
    84: "Detects auto-generated pagination parameter explosion, creating many near-duplicate URLs and wasting crawl budget.",
    85: "Assesses adoption of next-gen image formats (WebP/AVIF), which are smaller and faster than JPEG/PNG.",
    86: "Checks for preload hints on key requests, which can prioritise critical resources and improve load speed.",
    87: "Checks whether the LCP element is preloaded, which can meaningfully improve Largest Contentful Paint.",
    88: "Checks whether heavy third-party embeds are lazy-loaded with facades, reducing their performance impact.",
    89: "Detects the same script loaded more than once on a page, wasting bandwidth and slowing execution.",
    90: "Detects content hidden with display:none. Hidden content carries little/no SEO value and may signal cloaking if abused.",
}


def describe(num: int) -> str:
    return DESCRIPTIONS.get(num, "")
